"""Init migration

Revision ID: 3c0a58aeca43
Revises: 
Create Date: 2022-05-13 20:36:16.393714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0a58aeca43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=25), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=1023), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('comments',
    sa.Column('pk', sa.String(length=48), nullable=False),
    sa.Column('comment_details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('pk')
    )
    op.create_table('managers',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('pk', sa.String(length=48), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('manager_id', sa.String(length=48), nullable=True),
    sa.Column('order_name', sa.String(length=255), nullable=False),
    sa.Column('order_details', sa.Text(), nullable=False),
    sa.Column('order_status', sa.Enum('Free', 'InWork', 'Delivery', 'Done', name='orderstatus'), nullable=True),
    sa.Column('sphere_type', sa.Enum('Shop', 'Social', 'Government', 'Artist', 'Business', name='spheretype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('pk')
    )
    op.create_table('order_comment_association',
    sa.Column('order_pk', sa.String(length=48), nullable=True),
    sa.Column('comment_pk', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['comment_pk'], ['comments.pk'], ),
    sa.ForeignKeyConstraint(['order_pk'], ['orders.pk'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_comment_association')
    op.drop_table('orders')
    op.drop_table('managers')
    op.drop_table('comments')
    op.drop_table('clients')
    op.drop_table('admins')
    # ### end Alembic commands ###
